server:
  address: 0.0.0.0
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&createDatabaseIfNotExist=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: update
    generate-ddl: true

logging:
  level:
    cn.techial: debug
    org.springframework.security: DEBUG

wechat:
  client:
    clientId:
    clientSecret:
    accessTokenUri: https://api.weixin.qq.com/sns/oauth2/access_token
    userAuthorizationUri: https://open.weixin.qq.com/connect/oauth2/authorize
    tokenName: access_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: snsapi_userinfo
  resource:
    userInfoUri: https://api.weixin.qq.com/sns/userinfo
