server:
  address: 0.0.0.0
  port: 80

spring:
  security:
    user:
      password: '{noop}root'
      name: 'root'

security:
  login-page: /login
  login-processing-url: /api/user/login
  ant-matchers:
    - /api/home**/**
  mvc-matchers:
    - /api/user/**
    - /api/index**/**

wechat:
  client:
    clientId: <input client id>
    clientSecret: <input client secret>
    accessTokenUri: https://api.weixin.qq.com/sns/oauth2/access_token
    userAuthorizationUri: https://open.weixin.qq.com/connect/oauth2/authorize
    tokenName: access_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: snsapi_userinfo
  resource:
    userInfoUri: https://api.weixin.qq.com/sns/userinfo
  config:
    app-id: appid
    client-id: client_id
    secret: secret
    client-secret: client_secret
    state: state
    wechat-redirect: wechat_redirect

logging:
  level:
    cn.techial: debug
    org.springframework.security: DEBUG
